spring:
  profiles:
    active: prod # 기본 환경 선택

--- # 운영 환경

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://alcoholic-db.c9kvlhuupzii.ap-northeast-2.rds.amazonaws.com:3306/alcoholic_db?serverTimezone=Asia/Seoul
    username: root
    password: alcoholic1!

  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    password: alcoholic1!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 785773674777-v891sf1pls1v5uhqrim7f6djad8oel6m.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email, https://www.googleapis.com/auth/user.birthday.read
          kakao:
            client-id: 9182d496ee2d4e3865ddb36e8d01b08e
            client-secret: 5nfNTKsvZ4r2Dx6mUILzzY7tpUMrNpfY
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            # redirect-uri: "http://localhost:8080/login-success"
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: INFO
    org.hibernate.type: trace
    com.example.ayoteralab.main: DEBUG
  file:
    path: logs

security:
  basic:
    enabled: false

member:
  default:
    image: default_user.jpeg


jwt:
  secret: "secret hello world fdslkjflsdjfjsdjfiejwofjlksdjlfjkldsfjlkjlskdjflk"