spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
    username: root
    password: alcoholic1!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 785773674777-v891sf1pls1v5uhqrim7f6djad8oel6m.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email, https://www.googleapis.com/auth/user.birthday.read
          kakao:
            client-id: 9182d496ee2d4e3865ddb36e8d01b08e
            client-secret: 5nfNTKsvZ4r2Dx6mUILzzY7tpUMrNpfY
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            # redirect-uri: "http://localhost:8080/login-success"
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    root: INFO
    org.hibernate.type: trace
    com.example.ayoteralab.main: DEBUG
  file:
    path: logs

security:
  basic:
    enabled: false
