spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
    username: root
    password: alcoholic1!

  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    password: alcoholic1!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 785773674777-v891sf1pls1v5uhqrim7f6djad8oel6m.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 9182d496ee2d4e3865ddb36e8d01b08e
            client-secret: 5nfNTKsvZ4r2Dx6mUILzzY7tpUMrNpfY
            scope: profile_nickname, profile_image, account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: shiningcastle.dev@gmail.com
    password: lelpbrlqlqhpkenw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

cloud:
  aws:
    credentials:
      access-key: AKIAXM3ICDO2CMT43JFD
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: alcoholics3
      suffix-url: s3.ap-northeast-2.amazonaws.com

logging:
  level:
    root: INFO
    org.hibernate.type:
      descriptor:
        sql: trace
    com.example.ayoteralab.main: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
  file:
    path: logs

security:
  basic:
    enabled: false

jwt:
  secret: "secret hello world fdslkjflsdjfjsdjfiejwofjlksdjlfjkldsfjlkjlskdjflk"

image:
  member:
    directory: member
    default: default.png
  board:
    directory: board

mail:
  minutes: 5
  hours: 2
  link: <h2><a href='http://localhost:8080/api/mail/auth/%s?email=%s&number=%d'>인증하기</a></h2>
  response: <script>alert('이메일 인증 성공.\nAlcoholic 페이지로 돌아가 남은 절차를 진행해주세요.'); window.close();</script>

front:
  url: https://alcoholic.ml

oauth:
  new-suffix:
      /signup/nickname
